//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Phone.Controls.LocalizedResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Phone.Controls.LocalizedResources.ControlResources", typeof(ControlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about a minute ago.
        /// </summary>
        public static string AboutAMinuteAgo {
            get {
                return ResourceManager.GetString("AboutAMinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about a month ago.
        /// </summary>
        public static string AboutAMonthAgo {
            get {
                return ResourceManager.GetString("AboutAMonthAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about an hour ago.
        /// </summary>
        public static string AboutAnHourAgo {
            get {
                return ResourceManager.GetString("AboutAnHourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about a week ago.
        /// </summary>
        public static string AboutAWeekAgo {
            get {
                return ResourceManager.GetString("AboutAWeekAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALARM REPEATS ON.
        /// </summary>
        public static string AlarmRepeatsOn {
            get {
                return ResourceManager.GetString("AlarmRepeatsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bytes.
        /// </summary>
        public static string Byte {
            get {
                return ResourceManager.GetString("Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE DATE.
        /// </summary>
        public static string DatePickerTitle {
            get {
                return ResourceManager.GetString("DatePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string DateTimePickerCancelText {
            get {
                return ResourceManager.GetString("DateTimePickerCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string DateTimePickerDoneText {
            get {
                return ResourceManager.GetString("DateTimePickerDoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        public static string Gigabyte {
            get {
                return ResourceManager.GetString("Gigabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        public static string Kilobyte {
            get {
                return ResourceManager.GetString("Kilobyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last Friday.
        /// </summary>
        public static string last_Friday {
            get {
                return ResourceManager.GetString("last Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last Monday.
        /// </summary>
        public static string last_Monday {
            get {
                return ResourceManager.GetString("last Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last Saturday.
        /// </summary>
        public static string last_Saturday {
            get {
                return ResourceManager.GetString("last Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last Sunday.
        /// </summary>
        public static string last_Sunday {
            get {
                return ResourceManager.GetString("last Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last Thursday.
        /// </summary>
        public static string last_Thursday {
            get {
                return ResourceManager.GetString("last Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last Tuesday.
        /// </summary>
        public static string last_Tuesday {
            get {
                return ResourceManager.GetString("last Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last Wednesday.
        /// </summary>
        public static string last_Wednesday {
            get {
                return ResourceManager.GetString("last Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string Megabyte {
            get {
                return ResourceManager.GetString("Megabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on Friday.
        /// </summary>
        public static string on_Friday {
            get {
                return ResourceManager.GetString("on Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on Monday.
        /// </summary>
        public static string on_Monday {
            get {
                return ResourceManager.GetString("on Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on Saturday.
        /// </summary>
        public static string on_Saturday {
            get {
                return ResourceManager.GetString("on Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on Sunday.
        /// </summary>
        public static string on_Sunday {
            get {
                return ResourceManager.GetString("on Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on Thursday.
        /// </summary>
        public static string on_Thursday {
            get {
                return ResourceManager.GetString("on Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on Tuesday.
        /// </summary>
        public static string on_Tuesday {
            get {
                return ResourceManager.GetString("on Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on Wednesday.
        /// </summary>
        public static string on_Wednesday {
            get {
                return ResourceManager.GetString("on Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to over a year ago.
        /// </summary>
        public static string OverAYearAgo {
            get {
                return ResourceManager.GetString("OverAYearAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        public static string PartOfWhole {
            get {
                return ResourceManager.GetString("PartOfWhole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every day.
        /// </summary>
        public static string RepeatsEveryDay {
            get {
                return ResourceManager.GetString("RepeatsEveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only once.
        /// </summary>
        public static string RepeatsOnlyOnce {
            get {
                return ResourceManager.GetString("RepeatsOnlyOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weekdays.
        /// </summary>
        public static string RepeatsOnWeekdays {
            get {
                return ResourceManager.GetString("RepeatsOnWeekdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weekends.
        /// </summary>
        public static string RepeatsOnWeekends {
            get {
                return ResourceManager.GetString("RepeatsOnWeekends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string StatusCancelled {
            get {
                return ResourceManager.GetString("StatusCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complete.
        /// </summary>
        public static string StatusComplete {
            get {
                return ResourceManager.GetString("StatusComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string StatusDownloading {
            get {
                return ResourceManager.GetString("StatusDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string StatusFailed {
            get {
                return ResourceManager.GetString("StatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paused.
        /// </summary>
        public static string StatusPaused {
            get {
                return ResourceManager.GetString("StatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string StatusPending {
            get {
                return ResourceManager.GetString("StatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        public static string StatusUnknown {
            get {
                return ResourceManager.GetString("StatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        public static string StatusUploading {
            get {
                return ResourceManager.GetString("StatusUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting....
        /// </summary>
        public static string StatusWaiting {
            get {
                return ResourceManager.GetString("StatusWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting....
        /// </summary>
        public static string StatusWaitingForExternalPower {
            get {
                return ResourceManager.GetString("StatusWaitingForExternalPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low battery.
        /// </summary>
        public static string StatusWaitingForExternalPowerDueToBatterySaverMode {
            get {
                return ResourceManager.GetString("StatusWaitingForExternalPowerDueToBatterySaverMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for connection.
        /// </summary>
        public static string StatusWaitingForNonVoiceBlockingNetwork {
            get {
                return ResourceManager.GetString("StatusWaitingForNonVoiceBlockingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Wi-Fi.
        /// </summary>
        public static string StatusWaitingForWiFi {
            get {
                return ResourceManager.GetString("StatusWaitingForWiFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE TIME.
        /// </summary>
        public static string TimePickerTitle {
            get {
                return ResourceManager.GetString("TimePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string XHoursAgo_2To4 {
            get {
                return ResourceManager.GetString("XHoursAgo_2To4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string XHoursAgo_EndsIn1Not11 {
            get {
                return ResourceManager.GetString("XHoursAgo_EndsIn1Not11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string XHoursAgo_EndsIn2To4Not12To14 {
            get {
                return ResourceManager.GetString("XHoursAgo_EndsIn2To4Not12To14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string XHoursAgo_Other {
            get {
                return ResourceManager.GetString("XHoursAgo_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        public static string XMinutesAgo_2To4 {
            get {
                return ResourceManager.GetString("XMinutesAgo_2To4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        public static string XMinutesAgo_EndsIn1Not11 {
            get {
                return ResourceManager.GetString("XMinutesAgo_EndsIn1Not11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        public static string XMinutesAgo_EndsIn2To4Not12To14 {
            get {
                return ResourceManager.GetString("XMinutesAgo_EndsIn2To4Not12To14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        public static string XMinutesAgo_Other {
            get {
                return ResourceManager.GetString("XMinutesAgo_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months ago.
        /// </summary>
        public static string XMonthsAgo_2To4 {
            get {
                return ResourceManager.GetString("XMonthsAgo_2To4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months ago.
        /// </summary>
        public static string XMonthsAgo_5To12 {
            get {
                return ResourceManager.GetString("XMonthsAgo_5To12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds ago.
        /// </summary>
        public static string XSecondsAgo_2To4 {
            get {
                return ResourceManager.GetString("XSecondsAgo_2To4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds ago.
        /// </summary>
        public static string XSecondsAgo_EndsIn1Not11 {
            get {
                return ResourceManager.GetString("XSecondsAgo_EndsIn1Not11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds ago.
        /// </summary>
        public static string XSecondsAgo_EndsIn2To4Not12To14 {
            get {
                return ResourceManager.GetString("XSecondsAgo_EndsIn2To4Not12To14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds ago.
        /// </summary>
        public static string XSecondsAgo_Other {
            get {
                return ResourceManager.GetString("XSecondsAgo_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} weeks ago.
        /// </summary>
        public static string XWeeksAgo_2To4 {
            get {
                return ResourceManager.GetString("XWeeksAgo_2To4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
